
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
endpoints:
  shutdown:
    enabled: true
    sensitive: false
logging:
  level:
    org:
      springframework:
        web: DEBUG
  file: /data/logs/etrade-server-demo/log.log
server:
  port: 8088